server.port: 7001
server.error.include-message: always

spring.application.name: receivable
spring.jackson.deserialization.fail-on-unknown-properties: true

spring.data.mongodb:
  host: localhost
  port: 27017
  database: receivable-db

logging:
  level:
    root: INFO
    ch.canaweb: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
---
spring.config.activate.on-profile: docker

server.port: 8080


spring.data.mongodb.host: mongodb

---
spring.config.activate.on-profile: prod

