server.error.include-message: always

logging:
  level:
    root: INFO
    ch.canaweb: DEBUG

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---
spring.config.activate.on-profile: docker
server.port: 8080

app:
  field-service:
    host: field
    port: 8080
  payable-service:
    host: payable
    port: 8080
  receivable-service:
    host: receivable
    port: 8080

---
spring.config.activate.on-profile: prod
