server.port: 7000
server.error.include-message: always

logging:
  level:
    root: INFO
    ch.canaweb: DEBUG

api:
  common:
    version: 0.1
    title: CanaWeb - GUI API
    description: Exposes the endpoints required for CanaWeb GUI.

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"


spring.application.name: field-composite

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

ribbon.ServerListRefreshInterval: 5000

ribbon.NFLoadBalancerPingInterval: 5

---
spring.config.activate.on-profile: docker

server.port: 8080

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/

spring:
  cloud:
    config:
      enabled: false
---
spring.config.activate.on-profile: prod
