server.error.include-message: always
canaweb_env: "DEV"

logging:
  level:
    root: INFO
    ch.canaweb: DEBUG

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
---
spring.config.activate.on-profile: docker
server.port: 8080
canaweb_env: "DOCKER"

---
spring.config.activate.on-profile: prod
canaweb_env: "PROD"
